services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - default
      - caddy
    labels:
      caddy: ctrlv.site
      caddy.reverse_proxy: "{{upstreams 8000}}"

  bot:
    build:
      context: .
      dockerfile: bot.Dockerfile
    env_file:
      - .env
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api

networks:
  caddy:
    external: true
